name: KiCad Visual Diff

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.kicad_pcb'
      - '**/*.kicad_sch'

jobs:
  visual_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup KiRI
        run: |
          # Hier kommen die Installationsbefehle für KiRI und seine Abhängigkeiten
          sudo apt-get update
          sudo apt-get install -y opam
          opam init --bare
          eval $(opam env)
          opam install kiri

      - name: Run KiRI Diff
        run: |
          kiri diff --output-dir diffs/

      - name: Upload visual diffs
        uses: actions/upload-artifact@v4
        with:
          name: kiri-diff-output
          path: diffs/